### ISSUE TITLE
addMessage() on null

### ISSUE THREAD

**Issue by loomanss** [akrabat/slim-bookshelf-api#2]
when logging in , i received te following error

Type: Error
Message: Call to a member function addMessage() on null
File: /slim-bookshelf-api/web/src/App/Action/LoginAction.php
Line: 36
LoginAction.php : Line 36 

`$this->flash->addMessage('error', "Failed to log in: " . $e->getMessage());`

**Comment by akrabat** [comment]
Fixed in master by #3.
